#!/usr/bin/env ruby

require 'retest'

$stdout.sync = true

options = Retest::Options.new(ARGV)

return puts options.help if options.help?

puts "Launching Retest..."

Retest
  .build(runner: Retest::Runner.for(options.command))
  .start # not blocking

puts "Ready to refactor! You can make file changes now"

sleep
